import Navbar from "../elements/Navbar";
import Head from "next/head";

interface PropType {
  children: React.ReactNode;
  title?: String;
}

export default function Layout({ children, title = "Simple Post" }: PropType) {
  return (
    <section className="lg:px-32 px-4">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </section>
  );
}
